#NumPy

[NumPy](https://numpy.org) is an open source project aiming to enable numerical computing with Python. It was created in 2005, building on the early work of the Numeric and Numarray libraries. NumPy will always be 100% open source software, free for all to use and released under the liberal terms of the modified BSD license.

Characteristics of Numpy:
*   Operations with N-dimensional arrays
*   Numerical computing tools
*   Interoperable
*   Well-optimised in C code


To use NumPy, you should import the numpy package



In [2]:
import numpy as np

##ndarray

The core of numpy is the ndarray, N-dimensional array. N-dimensional arrays contain numerical elements of the same type, and they are fixed-length data containers.

In [3]:
x = np.array([1, 2, 3])
print(x)
print(x.dtype) # dtype --> data type
print(x.shape) # x is anumpy array with 3 integer elements

[1 2 3]
int64
(3,)


In [4]:
y = np.array([[True, False], [False, True]])
print(y)
print(y.dtype)
print(y.shape) # y is a 2-dimensional array (2x2) of boolean elements

[[ True False]
 [False  True]]
bool
(2, 2)


##Vectorization

Vectorization is what makes NumPy fast. Vectorized operations in NumPy enable the use of efficient, pre-compiled functions and mathematical operations on NumPy arrays and data sequences. Vectorization is a method of performing array operations without the use of for loops.



In [5]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)
print(x, y)

[4 1 0 5 7 8 5 4 1 2] [9 7 6 2 8 9 8 1 1 6]


In [8]:
# Element wise addition of two arrays using loops
z = [x[i] + y[i] for i in range(10)]
print(z)

[13, 8, 6, 7, 15, 17, 13, 5, 2, 8]


In [9]:
# Element wise addition of two arrays using vectorization
z = x + y
print(z)

[13  8  6  7 15 17 13  5  2  8]


In [12]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
%timeit [a[i] + b[i] for i in range(a.shape[0])]

358 ms ± 15.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
# Element wise addition of two arrays using vectorization is 180 times faster than using loops
%timeit a + b

2.13 ms ± 83.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Vectorization is 180 faster than using a loop!!!

##Broadcasting
Elament-wise operations expand to the correct shape.

Broadcasting is easy and very fast.

In [ ]:
x = np.random.randint(0, 10, 10)
print(x)
y = x + 1 # adds 1 to each element of the array
print(y)

[0 8 2 7 4 8 8 9 4 4]
[ 1  9  3  8  5  9  9 10  5  5]


In [15]:
x = np.random.uniform(size=(2, 5))
print(x)
y = x + 1 # adds 1 to each element of the array
print(y)

[[0.16192031 0.08095365 0.80722963 0.46113236 0.59122585]
 [0.16688277 0.90472476 0.65214324 0.70697512 0.3021978 ]]
[[1.16192031 1.08095365 1.80722963 1.46113236 1.59122585]
 [1.16688277 1.90472476 1.65214324 1.70697512 1.3021978 ]]


Broadcasting when we add arrays of different shape.

In [16]:
x = np.random.randint(0, 10, 5)
y = np.random.uniform(size=(2, 5))
print(x)
print(y)
z = x + y # element-wise addition between the rows of x and y
print(z)
print(z.dtype, z.shape)

[0 1 4 8 6]
[[0.83613385 0.08279362 0.41215646 0.76489568 0.08724239]
 [0.06009691 0.29416064 0.27962638 0.03271174 0.07187586]]
[[0.83613385 1.08279362 4.41215646 8.76489568 6.08724239]
 [0.06009691 1.29416064 4.27962638 8.03271174 6.07187586]]
float64 (2, 5)


In [17]:
x = np.ones((5,2)) # an easy way to create an array with ones
print(x)
y = np.zeros((2,5)) # an easy way to create an array with zeros
print(y)
z = x.T + y
print(z)
zz = np.eye(5) # an easy way to create an identity matrix
print(zz)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##Element-wise operations
*   Arithmetic: `+`, `-`, `*`, `/`, `**`
*   Comparisons: `==`, `!=`, `<`, `>`, `<=`, `>=`



In [18]:
x = np.random.randint(0, 10, 5)
y = np.random.uniform(size=(2, 5))
print(x)
print(y)

[5 9 7 3 7]
[[0.63791703 0.0595636  0.80746497 0.99645034 0.77023575]
 [0.85718021 0.38318479 0.44323871 0.29922665 0.6591076 ]]


### Multiplication

In [20]:
z = x*y
print(z)

[[3.18958517 0.53607242 5.65225482 2.98935101 5.39165022]
 [4.28590103 3.44866309 3.102671   0.89767994 4.61375322]]


### Power

In [19]:
z = x**2
print(z)

[25 81 49  9 49]


### Comparison


In [21]:
z = x < y
print(z)

[[False False False False False]
 [False False False False False]]


In [22]:
z = x < 2
print(z)

[False False False False False]


##Methods for arrays
*   `.sum()`, `.mean()`, `.min()`, `.max()`, `.prod()`, `.cumsum()`, etc
*   `np.exp`, `np.log`, `np.sin`, `np.sqrt` etc

For all methods operating with ndarrays you can check the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

In [23]:
x = np.random.randint(0, 10, 10) # shape (10, )
print(x)
x = x.reshape((5,2)) # shape (2,5)
print(x)

[7 3 8 7 1 2 5 6 7 4]
[[7 3]
 [8 7]
 [1 2]
 [5 6]
 [7 4]]


In [24]:
z = x.sum() # the sum of all the elements
print(z)

50


In [25]:
z = x.sum(axis=1) # the sum across rows
print(z)

[10 15  3 11 11]


In [27]:
z = x.prod(axis=1) # the product across rows
print(z)

[21 56  2 30 28]


In [29]:
z = x.mean(axis=1) # the average across rows
print(z)

[5.  7.5 1.5 5.5 5.5]


In [31]:
print(x.min(), x.max()) # the minimum and the maximum element of the array

1 8


##Indexing and slicing
Indexing and slicing is similar to lists, but with multiple dimensions.

For a 2D matrix, the first index corresponds to rows and the second to columns.

In [32]:
x = np.random.randint(0, 10, 50) # shape (50, )
y = x.reshape((5,10)) # shape (5,10)
print(y)

[[4 2 7 2 8 2 3 5 8 7]
 [8 6 7 5 7 6 4 2 0 6]
 [1 7 7 0 9 3 2 0 7 1]
 [1 4 0 7 5 9 1 9 0 0]
 [6 0 2 6 9 3 0 5 1 1]]


In [33]:
row = y[0,:] # first row (indexing starts from 0)
print(row)
column = y[:,0] # first column.
print(column)

[4 2 7 2 8 2 3 5 8 7]
[4 8 1 1 6]


In [34]:
element = y[1][7] # the element from the 2nd row and 8th column
print(element)

2


In [35]:
element = y[1, 7] # alternative indexing that retrieves the same element as above
print(element)

2


In [36]:
submatrix = y[1:3, 5:9] # retrieves the elements from the 2nd and 3rd rows that also belong to the 6th, 7th, 8th and 9th columns
print(submatrix)

[[6 4 2 0]
 [3 2 0 7]]


In [37]:
last_row = y[-1] # the symbol minus before the index starts counting from the end
print(last_row)
last_column = y[:,-1]
print(last_column)

[6 0 2 6 9 3 0 5 1 1]
[7 6 1 0 1]


In [38]:
x = np.random.randint(0, 10, 105) # shape (105, )
y = x.reshape((3,5,7)) # shape (3,5,7)
print(y)

[[[6 9 6 7 3 3 6]
  [9 9 8 7 2 3 9]
  [7 8 8 8 8 3 1]
  [1 4 0 4 7 2 1]
  [1 3 3 0 4 9 9]]

 [[9 6 5 7 4 1 9]
  [5 2 2 3 0 1 1]
  [7 4 5 7 4 2 7]
  [0 0 8 6 9 5 2]
  [7 0 8 6 8 0 7]]

 [[9 9 9 3 1 6 8]
  [0 9 3 8 9 1 3]
  [6 7 8 6 8 8 6]
  [3 9 5 8 2 4 1]
  [8 2 8 1 5 3 5]]]


In [39]:
z = y[0,-1,2] # retrieves the element from the 1st matrix, last row, 3rd column
print(z)

3


In [40]:
z = y[0,:,:] # retrieves the 1st matrix
print(z)

[[6 9 6 7 3 3 6]
 [9 9 8 7 2 3 9]
 [7 8 8 8 8 3 1]
 [1 4 0 4 7 2 1]
 [1 3 3 0 4 9 9]]


In [41]:
z = y[:,0,:] # retrieves the first row from each matrix
print(z)

[[6 9 6 7 3 3 6]
 [9 6 5 7 4 1 9]
 [9 9 9 3 1 6 8]]


In [42]:
z = y[:,:,0] # retrieves the first column from each matrix
print(z)

[[6 9 7 1 1]
 [9 5 7 0 7]
 [9 0 6 3 8]]


###Boolean indexing
Another way to index ndarrays is by using boolean values.

In [43]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [44]:
boolean_indices = np.array([True,True,False,True,False])
z = x[boolean_indices] # retrieves those elements of x for which the boolean_indices are True
print(z)

[0 1 3]


In [45]:
even = (x % 2 == 0)
print(even)
z = x[even]
print(z)

[ True False  True False  True]
[0 2 4]


##Exercise
Write a function that uses as arguments the data matrix X below and the responses y and return the solution to the least square fitting.

The solution of least squares is given by $\beta=(X^TX)^{-1} X^T y$.
The fitted values are $\hat{y} = X(X^TX)^{-1} X^T y$

(Tip: the NumPy method `dot(x,y)` computes the [dot product](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) of `x` and `y`)

After fitting the model compute the Mean Square Error (true values - fitted values).

In [46]:
np.random.seed(1)
X = np.random.uniform(size=(100, 10))
y = np.random.uniform(size=(100,1))


In [47]:
def least_square_solution(X, y):
  XTX = np.dot(X.T, X)
  XTX_minus_1 = np.linalg.inv(XTX)
  XTy = np.dot(X.T, y)
  betas = np.dot(XTX_minus_1, XTy)
  return betas

b = least_square_solution(X, y)
print(b, b.shape)

y_hat = np.dot(X, b)
squared_error = (y - y_hat)**2
MSE = squared_error.mean()
print('MSE is {:.4f}'.format(MSE))

[[-0.0209993 ]
 [ 0.17063741]
 [ 0.1787921 ]
 [ 0.0675233 ]
 [ 0.24895156]
 [ 0.05521414]
 [ 0.17523039]
 [ 0.08515777]
 [ 0.03970765]
 [-0.02764994]] (10, 1)
MSE is 0.0844
